name: Deploy app
on:
  push:
    tags:
      - v*

env:
  DOCKER_IMAGE_NAME: ghcr.io/hybridfox/test-app

jobs:
  build-and-push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Create docker meta info
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy-to-development:
    name: Deploy to development
    needs: build-and-push
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Invoke update deployment workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: update-deployment
          repo: hybridfox/test-infra
          token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
          ref: master
          inputs: '{"filePath":"app/deployment.yaml","propertyPath":"spec.template.spec.containers.0.image","propertyValue":"${{ env.DOCKER_IMAGE_NAME }}:${{ github.event.release.tag_name }}"}'