name: Publish Docker image
on:
  push:
    tags:
      - v*

jobs:
  push-to-registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Create docker meta info
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/hybridfox/test-app
          tags: |
            type=semver,pattern={{version}}
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Invoke update deployment workflow
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: update-deployment
          repo: hybridfox/test-infra
          token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
          inputs: '{"filePath": "app/deployment.yaml","debug": true,"propertyPath": "spec.template.spec.containers.0.image","propertyValue": "ghcr.io/hybridfox/test-app:1.0.5"}'
          wait-for-completion: true